env:
  global:
  - SWIFT_BRANCH=swift-4.2.3-release
  - SWIFT_VERSION=swift-4.2.3-RELEASE

jobs:
  include:
  # The second stage will run all unit tests using Ubuntu
  - stage: Linux test
    os: linux
    language: generic
    dist: trusty
    sudo: required
    install:
    - sudo apt-get install clang libicu-dev
    - mkdir swift
    - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
    - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"
    script:
    - swift package update
    - swift test
  # The first stage will install swiftlint and check the code
  - stage: SwiftLint
    os: osx
    language: swift
    osx_image: xcode10.1
    sudo: required
    install:
    - ./script/install_swiftlint.sh
    script:
    - swiftlint
  # The third stage will run all tests on macOS
  - stage: OSX test
    os: osx
    osx_image: xcode10.1
    language: swift
    sudo: required
    install:
    - wget https://swift.org/builds/$SWIFT_BRANCH/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg
    - sudo installer -pkg $SWIFT_VERSION-osx.pkg -target /
    - export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
    script:
    - swift package update
    - swift test